TASK 1

In [11]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

In [13]:
gender = ['male', 'male', 'male', 'male', 'female', 'female', 'female', 'female']
height = [6.00, 5.92, 5.58, 5.92, 5.00, 5.50, 5.42, 5.75]
weight = [180, 190, 170, 165, 100, 150, 130, 150]
foot_size = [12, 11, 12, 10, 6, 8, 7, 9]

In [15]:
df = pd.DataFrame({
    'Gender': gender,
    'Height': height,
    'Weight': weight,
    'Foot_Size': foot_size
})

In [17]:
features = df[['Height', 'Weight', 'Foot_Size']]
labels = df['Gender']

In [19]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size=0.2, random_state=42)

In [21]:
classifier = DecisionTreeClassifier()
classifier = classifier.fit(features_train, labels_train)

In [23]:
new_entry = [[6.00, 180, 12]]
prediction = classifier.predict(new_entry)

C:\Users\KK Computers\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [25]:
labels_pred = classifier.predict(features_test)
conf_matrix = confusion_matrix(labels_test, labels_pred)
accuracy = accuracy_score(labels_test, labels_pred)

In [50]:
print("prediction: " +prediction[0])
print("Confution matrix:")
print(conf_matrix)
print("Accuracy: ",end="")
print(accuracy)

prediction: male
Confution matrix:
[[1 0]
 [0 1]]
Accuracy: 1.0


TASK 2

In [73]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

In [75]:
Gender = ['male', 'male', 'male', 'male', 'female', 'female', 'female', 'female']
Height = [6.00, 5.92, 5.58, 5.92, 5.00, 5.50, 5.42, 5.75]
Weight = [180, 190, 170, 165, 100, 150, 130, 150]
Foot_Size = [12, 11, 12, 10, 6, 8, 7, 9]

In [77]:
features = pd.DataFrame({'Height': Height, 'Weight': Weight, 'Foot_Size': Foot_Size})
labels = pd.Series(Gender)

In [79]:
new_entry = [6.00, 180, 12]
new_label = 'male'

In [81]:
new_features = pd.DataFrame([new_entry], columns=['Height', 'Weight', 'Foot_Size'])
features = pd.concat([features, new_features], ignore_index=True)
labels = pd.concat([labels, pd.Series([new_label])], ignore_index=True)

In [83]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size=0.2, random_state=42)

In [85]:
classifier = DecisionTreeClassifier()
classifier = classifier.fit(features_train, labels_train)

In [87]:
labels_pred = classifier.predict(features_test)
conf_matrix = confusion_matrix(labels_test, labels_pred)
accuracy = accuracy_score(labels_test, labels_pred)

In [89]:
print("prediction: " +prediction[0])
print("Confution matrix:")
print(conf_matrix)
print("Accuracy: ",end="")
print(accuracy)

prediction: male
Confution matrix:
[[1 0]
 [0 1]]
Accuracy: 1.0


TASK 3

In [101]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

In [103]:
Gender = np.array(['male', 'male', 'male', 'male', 'female', 'female', 'female', 'female'])
Height = np.array([6.00, 5.92, 5.58, 5.92, 5.00, 5.50, 5.42, 5.75])
Weight = np.array([180, 190, 170, 165, 100, 150, 130, 150])
Foot_Size = np.array([12, 11, 12, 10, 6, 8, 7, 9])

In [105]:
features = np.column_stack((Height, Weight, Foot_Size))

In [107]:
labels = Gender

In [109]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size=0.2, random_state=42)

In [111]:
classifier = DecisionTreeClassifier()
classifier = classifier.fit(features_train, labels_train)

In [113]:
new_entry = np.array([[6.00, 180, 12]])
prediction = classifier.predict(new_entry)
print(prediction[0])

male


In [115]:
labels_pred = classifier.predict(features_test)
conf_matrix = confusion_matrix(labels_test, labels_pred)
accuracy = accuracy_score(labels_test, labels_pred)

In [119]:
print("prediction: " +prediction[0])
print("Confution matrix:")
print(conf_matrix)
print("Accuracy: ",end="")
print(accuracy)

prediction: male
Confution matrix:
[[1 0]
 [0 1]]
Accuracy: 1.0


HOME ASSIGNMENT

In [189]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [190]:
Grade = ['High', 'Medium', 'Low', 'High', 'Low', 'Medium', 'Medium', 'High']
Extracurricular_Activities = ['Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes']
Recommendation_Letter = ['Strong', 'Weak', 'Average', 'Strong', 'Weak', 'Average', 'Strong', 'Strong']
Interview_Performance = ['Excellent', 'Good', 'Poor', 'Excellent', 'Good', 'Poor', 'Good', 'Excellent']
Admission = ['Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes']

In [191]:
features = pd.DataFrame({
    'Grade': Grade,
    'Extracurricular_Activities': Extracurricular_Activities,
    'Recommendation_Letter': Recommendation_Letter,
    'Interview_Performance': Interview_Performance
})
labels = pd.Series(Admission)

In [192]:
encoder = LabelEncoder()
features['Grade'] = encoder.fit_transform(features['Grade'])  
features['Extracurricular_Activities'] = encoder.fit_transform(features['Extracurricular_Activities'])
features['Recommendation_Letter'] = encoder.fit_transform(features['Recommendation_Letter'])
features['Interview_Performance'] = encoder.fit_transform(features['Interview_Performance'])
labels = encoder.fit_transform(labels)

In [193]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size=0.4, random_state=42)

In [194]:
classifier = DecisionTreeClassifier()
classifier = classifier.fit(features_train, labels_train)

In [195]:
new_entry = [[0, 1, 0, 2]]  
prediction = classifier.predict(new_entry)
print(f"Prediction for new entry: {'Yes' if prediction[0] == 1 else 'No'}")

Prediction for new entry: No


C:\Users\KK Computers\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [196]:
labels_pred = classifier.predict(features_test)
conf_matrix = confusion_matrix(labels_test, labels_pred)
accuracy = accuracy_score(labels_test, labels_pred)

In [197]:
print("Confusion Matrix:")
print(conf_matrix)
print(f"Accuracy: {accuracy * 100:.2f}%")

Confusion Matrix:
[[0 2]
 [0 2]]
Accuracy: 50.00%
